#!/usr/bin/env python
import os
import sys
import shutil

argv = sys.argv[1:]

if len(argv) == 0:
    print("fake git version 0.0")
    sys.exit(1)
if argv[0] == 'clone':
    print("fake git clone: {}".format(argv[1:]))
    if len(argv) == 2:
        # Get the basename of the module
        name = argv[1]
        name = name[name.rfind('/') + 1:-4]
        modpath = os.path.join(os.path.dirname(__file__), '..', 'modules', name)
        if os.path.exists(name):
            sys.exit(0)
        print("fake git cloning {} from {}".format(name, modpath))
        # Copy all the files
        shutil.copytree(modpath, name)
        sys.exit(0)
    else:
        print("unhandled fake git clone")
        sys.exit(1)
elif argv[0] == 'submodule':
    if argv[1:] == ['init']:
        sys.exit(0)
    elif argv[1:] == ['update', '--recursive']:
        sys.exit(0)

print("fake git unknown command: {}".format(argv))
sys.exit(1)
